CREATE TABLE IF NOT EXISTS public.porachki_materiali (
    id bigint generated by default as identity primary key,
    "Материал" text not null,
    "Дата на поръчка" date default current_date,
    "Доставчик" text,
    "Имейл на доставчик" text,
    "Количество" numeric not null default 1,
    "Дата на приемане" date,
    "Статус" text not null default 'Поръчано',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Обновяване на кеша (Schema Cache) за всеки случай, за да разпознае новата таблица веднага
NOTIFY pgrst, 'reload schema';
