-- 1. Създаване на таблицата за Хронология (Audit Logs)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint generated by default as identity primary key,
    table_name text not null,
    action_type text not null,
    old_data jsonb,
    new_data jsonb,
    changed_at timestamp with time zone default now()
);

-- Позволяваме на всички да четат (за да може Админ панелът да ги зарежда)
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON public.audit_logs;
CREATE POLICY "Enable read access for all users" ON public.audit_logs FOR SELECT USING (true);

-- 2. Създаване на универсалната функция-тригер
CREATE OR REPLACE FUNCTION public.audit_log_trigger()
RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        INSERT INTO public.audit_logs (table_name, action_type, old_data, changed_at)
        VALUES (TG_TABLE_NAME, TG_OP, row_to_json(OLD)::jsonb, now());
        RETURN OLD;
    ELSIF TG_OP = 'UPDATE' THEN
        -- Записваме само ако има реална промяна в данните
        IF row_to_json(OLD)::jsonb IS DISTINCT FROM row_to_json(NEW)::jsonb THEN
            INSERT INTO public.audit_logs (table_name, action_type, old_data, new_data, changed_at)
            VALUES (TG_TABLE_NAME, TG_OP, row_to_json(OLD)::jsonb, row_to_json(NEW)::jsonb, now());
        END IF;
        RETURN NEW;
    ELSIF TG_OP = 'INSERT' THEN
        INSERT INTO public.audit_logs (table_name, action_type, new_data, changed_at)
        VALUES (TG_TABLE_NAME, TG_OP, row_to_json(NEW)::jsonb, now());
        RETURN NEW;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Закачане на тригера към избраните таблици
DO $$
DECLARE
    t text;
BEGIN
    FOR t IN SELECT unnest(ARRAY['plan', 'marshruti', 'bom', 'Номенклатура', 'sklad'])
    LOOP
        EXECUTE format('DROP TRIGGER IF EXISTS trg_audit_log ON public.%I', t);
        EXECUTE format('CREATE TRIGGER trg_audit_log AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.audit_log_trigger()', t);
    END LOOP;
END;
$$;

-- 4. Добавени нови колони
ALTER TABLE public.marshruti ADD COLUMN IF NOT EXISTS "Инструкция за оставяне" text;
ALTER TABLE public.bom ADD COLUMN IF NOT EXISTS "Влага се на Оп. №" numeric;
