-- 1. Създаване на таблицата за Хронология (Audit Logs)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id bigint generated by default as identity primary key,
    table_name text not null,
    action_type text not null,
    old_data jsonb,
    new_data jsonb,
    changed_at timestamp with time zone default now()
);
